version: '3.7'

services:
  cryptopro:
    container_name: 'cryptopro'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CERTIFICATE_PIN: testcer
        # LICENSE:
    ports:
      - "3037:3037"
    restart: unless-stopped
    environment:
      - CERTIFICATE_PIN=testcer
